spring.application.name=ms-barriodigital-bff
server.port=${SERVER_PORT:8080}
spring.config.import=optional:file:.env[.properties],optional:file:./barriodigitalbff/.env[.properties]

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0

barriodigital.security.audience=${AZURE_API_AUDIENCE}

barriodigital.frontend.origin=${FRONTEND_ORIGIN:http://localhost:5173}

barriodigital.services.requests-url=${REQUESTS_SERVICE_URL:http://localhost:8081}
barriodigital.services.catalog-url=${CATALOG_SERVICE_URL:http://localhost:8082}

barriodigital.services.report-url=${REPORT_SERVICE_URL:http://localhost:8083}
barriodigital.services.audit-url=${AUDIT_SERVICE_URL:http://localhost:8084}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

server.error.include-stacktrace=never
server.error.include-message=never